import UIKit

/*
 
 PROBLEM-2
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the firstterms will be:
 
                    1,2,3,5,8,13,21,34,55,89,...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
*/

var numbers = [Int]()

numbers.append(1)
numbers.append(2)


var index = 0
var sumOfEvenNumbers = 0

repeat {
    
    numbers.append(numbers[index] + numbers[index + 1])
    
    if numbers[index] % 2 == 0 {
        sumOfEvenNumbers += numbers[index]
    }
    
    index += 1
    
} while numbers[index] < 4_000_000

print(sumOfEvenNumbers)

